cameras:
  entrance_cam:
    source: "samples/entrance.mp4"
    zones:
      - name: Entrance
        polygon:
          - [0.05, 0.95]
          - [0.30, 0.95]
          - [0.30, 0.60]
          - [0.05, 0.60]
      - name: Corridor
        polygon:
          - [0.35, 0.90]
          - [0.65, 0.90]
          - [0.65, 0.45]
          - [0.35, 0.45]
  lobby_cam:
    source: "samples/lobby.mp4"
    zones:
      - name: Lobby
        polygon:
          - [0.10, 0.85]
          - [0.90, 0.85]
          - [0.90, 0.55]
          - [0.10, 0.55]
      - name: Corridor
        polygon:
          - [0.20, 0.50]
          - [0.80, 0.50]
          - [0.80, 0.20]
          - [0.20, 0.20]
