anomaly_threshold: 0.75
code_red_classes:
  - Shooting
  - Assault
  - Robbery
  - Arson
  - Explosion
code_yellow_classes:
  - Fighting
  - Burglary
  - Vandalism
  - Shoplifting
  - Stealing
  - RoadAccidents
  - Abuse
  - Arrest
ci_min_for_alert: 0.75
cooldown_seconds: 30
window_frames: 32
stride_frames: 3
